DROP TABLE FRUIT IF EXISTS;
CREATE TABLE FRUIT(ID INT, NAME VARCHAR);
INSERT INTO FRUIT VALUES(1,'Apple');
INSERT INTO FRUIT VALUES(2,'Pear');
INSERT INTO FRUIT VALUES(3,'Cherry');
INSERT INTO FRUIT VALUES(4,'Banana');

DROP TABLE FRUIT_EXPORT IF EXISTS;
CREATE TABLE FRUIT_EXPORT(ID INT, FRUIT_ID INT,COUNTRY VARCHAR,QUANTITY INT);
INSERT INTO FRUIT_EXPORT VALUES(1,1,'USA', 500);
INSERT INTO FRUIT_EXPORT VALUES(2,1,'USA', 501);
INSERT INTO FRUIT_EXPORT VALUES(3,1,'Canada', 600);
INSERT INTO FRUIT_EXPORT VALUES(4,2,'Holland', 550);
INSERT INTO FRUIT_EXPORT VALUES(5,3,'Canada', 700);
INSERT INTO FRUIT_EXPORT VALUES(6,3,'Germany', 400);
INSERT INTO FRUIT_EXPORT VALUES(7,4,'USA', 540);